# Generated by Django 4.2.2 on 2023-07-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_lacality_customer_locality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
    ]
